use qedty_core::{canonical_json, deterministic_id, ecef_wgs84};
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct IdentityVector {
    kind: String,
    namespace: String,
    parts: Vec<Value>,
    length: usize,
    expected_id: String,
}

#[derive(Debug, Deserialize)]
struct JsonVector {
    kind: String,
    value: Value,
    expected: String,
}

#[derive(Debug, Deserialize)]
struct GeometryVector {
    kind: String,
    latitude: f64,
    longitude: f64,
    height_m: f64,
    expected_ecef_m: [f64; 3],
    absolute_tolerance_m: f64,
}

#[test]
fn identity_vector_matches() {
    let raw = include_str!("../../../data/contracts/golden-vectors/core/identity.json")
        .trim_start_matches('\u{feff}');
    let vector: IdentityVector = serde_json::from_str(raw).unwrap();
    assert_eq!(vector.kind, "identity");
    let actual = deterministic_id(
        &vector.kind,
        &vector.namespace,
        &vector.parts,
        vector.length,
    )
    .unwrap();
    assert_eq!(actual, vector.expected_id);
}

#[test]
fn canonical_json_vector_matches() {
    let raw = include_str!("../../../data/contracts/golden-vectors/core/canonical_json.json")
        .trim_start_matches('\u{feff}');
    let vector: JsonVector = serde_json::from_str(raw).unwrap();
    assert_eq!(vector.kind, "canonical_json");
    assert_eq!(canonical_json(&vector.value).unwrap(), vector.expected);
}

fn assert_geometry_vector(raw: &str, label: &str) {
    let vector: GeometryVector = serde_json::from_str(raw).unwrap_or_else(|error| {
        panic!("{label}: invalid shared geometry vector: {error}");
    });
    assert_eq!(vector.kind, "geometry_ecef", "{label}");

    let actual = ecef_wgs84(vector.latitude, vector.longitude, vector.height_m);
    let actual_array = [actual.0, actual.1, actual.2];
    for (axis, (actual_value, expected_value)) in
        actual_array.iter().zip(vector.expected_ecef_m).enumerate()
    {
        assert!(
            actual_value.is_finite()
                && (actual_value - expected_value).abs() <= vector.absolute_tolerance_m,
            "{label}: legacy ECEF axis {axis}: actual={actual_value}, expected={expected_value}, tolerance={} m",
            vector.absolute_tolerance_m
        );
    }

    let checked =
        qedty_core::geometry::try_ecef_wgs84(vector.latitude, vector.longitude, vector.height_m)
            .unwrap_or_else(|error| panic!("{label}: valid coordinate rejected: {error}"));
    let checked_array = [checked.x_m, checked.y_m, checked.z_m];
    for (axis, (actual_value, expected_value)) in
        checked_array.iter().zip(vector.expected_ecef_m).enumerate()
    {
        assert!(
            actual_value.is_finite()
                && (actual_value - expected_value).abs() <= vector.absolute_tolerance_m,
            "{label}: checked ECEF axis {axis}: actual={actual_value}, expected={expected_value}, tolerance={} m",
            vector.absolute_tolerance_m
        );
    }
}

#[test]
fn geometry_vector_matches() {
    let raw = include_str!("../../../data/contracts/golden-vectors/core/geometry_ecef.json")
        .trim_start_matches('\u{feff}');
    assert_geometry_vector(raw, "geometry_ecef.json");
}

#[test]
fn geometry_edge_reference_vectors_match() {
    // Reviewed axis/boundary vectors use the WGS-84 defining ellipsoid:
    // a = 6,378,137 m; inverse flattening = 298.257223563 (EPSG:7030).
    // Expected axis coordinates are independent exact/closed-form values,
    // not values generated by the Rust implementation under test.
    let vectors = [
        (
            "geometry_ecef_equator.json",
            include_str!("../../../data/contracts/golden-vectors/core/geometry_ecef_equator.json"),
        ),
        (
            "geometry_ecef_east_quarter_turn.json",
            include_str!(
                "../../../data/contracts/golden-vectors/core/geometry_ecef_east_quarter_turn.json"
            ),
        ),
        (
            "geometry_ecef_north_pole.json",
            include_str!(
                "../../../data/contracts/golden-vectors/core/geometry_ecef_north_pole.json"
            ),
        ),
        (
            "geometry_ecef_south_pole.json",
            include_str!(
                "../../../data/contracts/golden-vectors/core/geometry_ecef_south_pole.json"
            ),
        ),
        (
            "geometry_ecef_antimeridian.json",
            include_str!(
                "../../../data/contracts/golden-vectors/core/geometry_ecef_antimeridian.json"
            ),
        ),
        (
            "geometry_ecef_negative_height.json",
            include_str!(
                "../../../data/contracts/golden-vectors/core/geometry_ecef_negative_height.json"
            ),
        ),
    ];

    for (label, raw) in vectors {
        assert_geometry_vector(raw.trim_start_matches('\u{feff}'), label);
    }
}
