name: SLSA Provenance
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
    with:
      base64-subjects: "" 
